### ISSUE TITLE
Depencies incomplete/incorrect

### ISSUE THREAD

**Issue by agbcix** [HSAnet/reverse-traceroute#1]
I tried to compile and run the server on Ubuntu 20.04.
As indicated by the requirements, I installed linux-image-virtual-hwe-20.04 and thus kernel 5.15.0.

After running `bash build_docker.sh` I got a binary, but I couldn't execute it:
```
./augsburg-traceroute-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./augsburg-traceroute-server)
```

I think, it's fair to say that running the server requires Ubuntu 22.04 (or maybe later).

**Comment by vhein99** [comment]
Hi,

the docker image used for compilation uses an ubuntu-22.04 image, which apparently ships with glibc2.34.
Could you try to replace line 13 of `server/src/Makefile` with the following line:
```
	clang-14 -Wall traceroute.c $(LIBBPF) $(INCLUDES) -o $@ -lelf -lz -static
```

When you run docker again, the binary should be statically linked and thus eliminate the dependency on glibc2.34.
Could you try this workaround and get back to me if it works?

**Comment by agbcix** [comment]
I tried the workaround.
Traceroute builds fine and I am able to run it on Ubuntu 20.04 with kernel 5.15.0.

I also tried the binary on an Ubuntu 20.04 without HWE kernel -- it fails to start. But this was to be expected.
