### ISSUE TITLE
Improvement: Accept "y" to proceed transmission of measurement

### ISSUE THREAD

**Issue by agbcix** [HSAnet/reverse-traceroute#2]
When using the `--transmit` flag one gets the following prompt:
```
Do you want to proceed [Yes/No]:
```
The capital letters indicate (to me) that it's enough to type `y`.
Only after looking into the code, I found that I have to type `yes`.

I suggest to accept `y` as a positive answer.

**Comment by vhein99** [comment]
Fixed by commit d4e2cecca77e7c1dd08252bb2ac875b371ac0209,
transmission will now accept both lower- and upper-case 'y' as confirmation in addition to the spelled out "yes".
