### ISSUE TITLE
libbpf: prog 'prog': failed to load: -22

### ISSUE THREAD

**Issue by vrootz** [HSAnet/reverse-traceroute#9]
Hi guys,
after the installation process finished, the service failed to run on Debian11.
I know that Debian11 is not the recommended OS for the setup, but maybe we can find a way to get it running.

**System:**
~# cat /etc/debian_version 
11.5

~# uname -a
Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Problem:**
~/reverse-traceroute/server# ./augsburg-traceroute-server -n 50000 -t 5000000000 enp1s0
libbpf: loading object 'traceroute' from buffer
libbpf: elf: section(2) .text, size 6176, link 0, flags 6, type=1
libbpf: sec '.text': found program 'session_timeout_callback' at insn offset 760 (6080 bytes), code size 12 insns (96 bytes)
libbpf: sec '.text': found program 'log_message' at insn offset 0 (0 bytes), code size 18 insns (144 bytes)
libbpf: sec '.text': found program 'probe_match' at insn offset 18 (144 bytes), code size 67 insns (536 bytes)
libbpf: sec '.text': found program 'probe_create' at insn offset 85 (680 bytes), code size 243 insns (1944 bytes)
libbpf: sec '.text': found program 'resize_l3hdr' at insn offset 328 (2624 bytes), code size 43 insns (344 bytes)
libbpf: sec '.text': found program 'response_create_err' at insn offset 371 (2968 bytes), code size 122 insns (976 bytes)
libbpf: sec '.text': found program 'response_create' at insn offset 493 (3944 bytes), code size 194 insns (1552 bytes)
libbpf: sec '.text': found program 'session_delete' at insn offset 687 (5496 bytes), code size 9 insns (72 bytes)
libbpf: sec '.text': found program 'session_find' at insn offset 696 (5568 bytes), code size 5 insns (40 bytes)
libbpf: sec '.text': found program 'session_add' at insn offset 701 (5608 bytes), code size 59 insns (472 bytes)
libbpf: elf: section(3) .rel.text, size 304, link 28, flags 40, type=9
libbpf: elf: section(4) tc, size 1920, link 0, flags 6, type=1
libbpf: sec 'tc': found program 'prog' at insn offset 0 (0 bytes), code size 240 insns (1920 bytes)
libbpf: elf: section(5) .reltc, size 128, link 28, flags 40, type=9
libbpf: elf: section(6) .maps, size 48, link 0, flags 3, type=1
libbpf: elf: section(7) .rodata, size 8, link 0, flags 2, type=1
libbpf: elf: section(8) license, size 4, link 0, flags 3, type=1
libbpf: license of traceroute is GPL
libbpf: elf: section(19) .BTF, size 11808, link 0, flags 0, type=1
libbpf: elf: section(21) .BTF.ext, size 9488, link 0, flags 0, type=1
libbpf: elf: section(28) .symtab, size 1440, link 1, flags 0, type=2
libbpf: looking for externs among 60 symbols...
libbpf: collected 0 externs total
libbpf: map 'log_buf': at sec_idx 6, offset 0.
libbpf: map 'log_buf': found type = 27.
libbpf: map 'log_buf': found max_entries = 131072.
libbpf: map 'map_sessions': at sec_idx 6, offset 16.
libbpf: map 'map_sessions': found type = 1.
libbpf: map 'map_sessions': found key [14], sz = 8.
libbpf: map 'map_sessions': found value [21], sz = 32.
libbpf: map 'map_sessions': found max_entries = 5000.
libbpf: map 'tracerou.rodata' (global data): at sec_idx 7, offset 0, flags 480.
libbpf: map 2 is "tracerou.rodata"
libbpf: sec '.rel.text': collecting relocation for section(2) '.text'
libbpf: sec '.rel.text': relo #0: insn #2 against 'log_buf'
libbpf: prog 'log_message': found map 0 (log_buf, sec 6, off 0) for insn #2
libbpf: sec '.rel.text': relo #1: insn #102 against 'resize_l3hdr'
libbpf: sec '.rel.text': relo #2: insn #154 against 'resize_l3hdr'
libbpf: sec '.rel.text': relo #3: insn #194 against 'resize_l3hdr'
libbpf: sec '.rel.text': relo #4: insn #384 against 'resize_l3hdr'
libbpf: sec '.rel.text': relo #5: insn #509 against 'resize_l3hdr'
libbpf: sec '.rel.text': relo #6: insn #690 against 'log_message'
libbpf: sec '.rel.text': relo #7: insn #691 against 'map_sessions'
libbpf: prog 'session_delete': found map 1 (map_sessions, sec 6, off 16) for insn #4
libbpf: sec '.rel.text': relo #8: insn #697 against 'map_sessions'
libbpf: prog 'session_find': found map 1 (map_sessions, sec 6, off 16) for insn #1
libbpf: sec '.rel.text': relo #9: insn #708 against 'map_sessions'
libbpf: prog 'session_add': found map 1 (map_sessions, sec 6, off 16) for insn #7
libbpf: sec '.rel.text': relo #10: insn #717 against 'map_sessions'
libbpf: prog 'session_add': found map 1 (map_sessions, sec 6, off 16) for insn #16
libbpf: sec '.rel.text': relo #11: insn #723 against 'map_sessions'
libbpf: prog 'session_add': found map 1 (map_sessions, sec 6, off 16) for insn #22
libbpf: sec '.rel.text': relo #12: insn #734 against 'map_sessions'
libbpf: prog 'session_add': found map 1 (map_sessions, sec 6, off 16) for insn #33
libbpf: sec '.rel.text': relo #13: insn #742 against '.text'
libbpf: sec '.rel.text': relo #14: insn #746 against 'TIMEOUT_NS'
libbpf: prog 'session_add': found data map 2 (tracerou.rodata, sec 7, off 0) for insn 45
libbpf: sec '.rel.text': relo #15: insn #756 against 'log_message'
libbpf: sec '.rel.text': relo #16: insn #762 against 'log_message'
libbpf: sec '.rel.text': relo #17: insn #765 against 'log_message'
libbpf: sec '.rel.text': relo #18: insn #766 against 'map_sessions'
libbpf: prog 'session_timeout_callback': found map 1 (map_sessions, sec 6, off 16) for insn #6
libbpf: sec '.reltc': collecting relocation for section(4) 'tc'
libbpf: sec '.reltc': relo #0: insn #101 against 'probe_create'
libbpf: sec '.reltc': relo #1: insn #112 against 'session_add'
libbpf: sec '.reltc': relo #2: insn #147 against 'probe_match'
libbpf: sec '.reltc': relo #3: insn #154 against 'session_find'
libbpf: sec '.reltc': relo #4: insn #161 against 'log_message'
libbpf: sec '.reltc': relo #5: insn #163 against 'session_delete'
libbpf: sec '.reltc': relo #6: insn #210 against 'response_create'
libbpf: sec '.reltc': relo #7: insn #233 against 'response_create_err'
libbpf: map 'log_buf': created successfully, fd=4
libbpf: map 'map_sessions': created successfully, fd=5
libbpf: map 'tracerou.rodata': created successfully, fd=6
libbpf: prog 'prog': added 243 insns from sub-prog 'probe_create'
libbpf: prog 'prog': added 43 insns from sub-prog 'resize_l3hdr'
libbpf: prog 'probe_create': insn #17 relocated, imm 225 points to subprog 'resize_l3hdr' (now at 483 offset)
libbpf: prog 'probe_create': insn #69 relocated, imm 173 points to subprog 'resize_l3hdr' (now at 483 offset)
libbpf: prog 'probe_create': insn #109 relocated, imm 133 points to subprog 'resize_l3hdr' (now at 483 offset)
libbpf: prog 'prog': insn #101 relocated, imm 138 points to subprog 'probe_create' (now at 240 offset)
libbpf: prog 'prog': added 59 insns from sub-prog 'session_add'
libbpf: prog 'prog': added 12 insns from sub-prog 'session_timeout_callback'
libbpf: prog 'prog': added 18 insns from sub-prog 'log_message'
libbpf: prog 'session_timeout_callback': insn #2 relocated, imm 9 points to subprog 'log_message' (now at 597 offset)
libbpf: prog 'session_timeout_callback': insn #5 relocated, imm 6 points to subprog 'log_message' (now at 597 offset)
libbpf: prog 'session_add': insn #41 relocated, imm 17 points to subprog 'session_timeout_callback' (now at 585 offset)
libbpf: prog 'session_add': insn #55 relocated, imm 15 points to subprog 'log_message' (now at 597 offset)
libbpf: prog 'prog': insn #112 relocated, imm 413 points to subprog 'session_add' (now at 526 offset)
libbpf: prog 'prog': added 67 insns from sub-prog 'probe_match'
libbpf: prog 'prog': insn #147 relocated, imm 467 points to subprog 'probe_match' (now at 615 offset)
libbpf: prog 'prog': added 5 insns from sub-prog 'session_find'
libbpf: prog 'prog': insn #154 relocated, imm 527 points to subprog 'session_find' (now at 682 offset)
libbpf: prog 'prog': insn #161 relocated, imm 435 points to subprog 'log_message' (now at 597 offset)
libbpf: prog 'prog': added 9 insns from sub-prog 'session_delete'
libbpf: prog 'session_delete': insn #3 relocated, imm -94 points to subprog 'log_message' (now at 597 offset)
libbpf: prog 'prog': insn #163 relocated, imm 523 points to subprog 'session_delete' (now at 687 offset)
libbpf: prog 'prog': added 194 insns from sub-prog 'response_create'
libbpf: prog 'response_create': insn #16 relocated, imm -230 points to subprog 'resize_l3hdr' (now at 483 offset)
libbpf: prog 'prog': insn #210 relocated, imm 485 points to subprog 'response_create' (now at 696 offset)
libbpf: prog 'prog': added 122 insns from sub-prog 'response_create_err'
libbpf: prog 'response_create_err': insn #13 relocated, imm -421 points to subprog 'resize_l3hdr' (now at 483 offset)
libbpf: prog 'prog': insn #233 relocated, imm 656 points to subprog 'response_create_err' (now at 890 offset)
libbpf: prog 'prog': BPF program load failed: Invalid argument
libbpf: prog 'prog': -- BEGIN PROG LOAD LOG --
number of funcs in func_info doesn't match number of subprogs
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: prog 'prog': failed to load: -22
libbpf: failed to load object 'traceroute'
libbpf: failed to load BPF skeleton 'traceroute': -22
Failed to load the program.

If you need any further information, let me know

**Comment by vhein99** [comment]
Hi,
the minimum required Linux kernel version is 5.15.0 as the program makes use of recent eBPF features such as timers.
You are trying to run it on a kernel version 5.10.0.
